services:
  wordpress:
    image: wordpress
    restart: always
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: myuser
      WORDPRESS_DB_PASSWORD: mypassword
      WORDPRESS_DB_NAME: wp_db
    volumes:
      - wordpress:/var/www/html
    depends_on: 
      - db
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: wp_db
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
      MYSQL_ROOT_PASSWORD: mypassword
    volumes:
      - db:/var/lib/mysql
volumes:
  wordpress:
  db:
